#SERVER CONFIGURATION
server: 
  port: ${PORT:8001}
  servlet:
    display-name: ecology-info
    
#SPRING COFIGURATION
spring:
   application:
      name: ecology-info
      
   datasource:
      #url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ecology?characterEncoding=UTF-8&serverTimezone=UTC
      url: jdbc:mysql://127.0.0.1:3306/ecology?characterEncoding=UTF-8&serverTimezone=UTC
      username: smluv82
      password: 1234qwer!@
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      continue-on-error: true
#      initialize: false
#      connection-timeout: 15000
#      validation-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 3600000
#      maximum-pool-size: 30
#      minimum-idle: 10
#      connection-test-query: SELECT 1
#      auto-commit: false

   jpa:
      hibernate:
#         ddl-auto: create
         ddl-auto: none
      generate-ddl: false
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      properties:
         hibernate:
            format_sql: true
            use_sql_comments: true

   redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
         pool:
            max-active: 8
            max-idle: 8
            max-wait: -1ms
            min-idle: 2

jwt:
   secret-key: smtestjwt
   expire: 30